.mergify.yml

chore(mergify): 忽略 dependabot 的 pr

---

.mergify.yml

* 使用label来指定需要自动合并的pr，这就相当于用添加label来代替以前的merge按钮
+ 添加 codecov 的检查

chore(mergify): 改变合并策略

---

crawler/crawlers/leetcode_cn.js

fix(爬虫): leetcode cn 在 左侧面板 badge 数量不一样时爬取错误

---

Makefile
build/docker-compose.dev-frontend.yml
build/docker-compose.dev.yml
build/docker-compose.mk
frontend/Makefile
frontend/nuxt.config.js

docker frontend dev

---

build/docker-compose.yml

ouroboros 有些bug，没法让重启的容器正常加入网络

fix(docker): 将 ouroboros 更换成 watchtower

---

crawler/lib/functionGenerator.js

目前会在爬虫代码抛出网络异常时使用服务器端爬虫重新爬取一遍，不会检测爬虫的运行时间长短。
resolve #462
refer to #398

feat(crawler): 在浏览器端爬虫遇到网络问题时切换到服务器端爬虫

---

frontend/components/WorkerCard.vue
frontend/package-lock.json
frontend/plugins/debug.js
frontend/store/-dynamic/statistics.js

可能还需要 https://github.com/Akryum/vue-virtual-scroller 之类的来优化题目列表。

优化statistics页面的渲染速度

---

.github/workflows/sonar-cloud.yml
.github/workflows/update-e2e-snapshot.yml
.travis.yml
frontend/.vscode/settings.json
sonar-project.properties

看起来workflow目前还不能单独重启单个job，整体迁移的计划稍作延后

将部分CI迁移到github workflow上

---

.travis.yml
build/docker-compose.mk

chore(travis): 让e2e输出镜像构建日志

---

e2e/__test__/pages/__snapshots__/pages_snapshot.test.js.snap
frontend/pages/statistics.vue

Add summary panel

---

LICENSE
README.md

chore(license): change license to AGPL-3.0

---

crawler/config.yml
crawler/crawlers/.eslintrc.js
crawler/crawlers/codeforces.js

So that the browser can detect 429 error

fix(crawler): fix codeforces in browser side crawler

---

backend/src/AcmStatisticsBackend.Core/Crawlers/SummaryGenerator.cs
backend/test/AcmStatisticsBackend.Tests/Crawlers/SummaryGenerator_Tests.cs
frontend/__test__/store/statistics.test.js

Add basic support of local judge in virtual judge

---

crawler/crawlers/uoj.js

It cannot handle user with submissions less than one page.
fix #1469

fix(crawler): fix submission error in uoj

---

build/docker-compose.yml

mbind: Operation not permitted
see: https://stackoverflow.com/a/55706057

fix(build): try fix database

---

Makefile
backend/src/AcmStatisticsBackend.Application/Crawlers/IDefaultQueryAppService.cs
frontend/Makefile

Translate Makefile

---

frontend/package-lock.json
frontend/package.json

Reverts Liu233w/acm-statistics#1902

Revert "chore(*): Update dependency @nuxtjs/vuetify to v1.12.1"

---

crawler/config.yml

feat(crawler): set luogu as server_only crawler

---

captcha-service/package.json
captcha-service/pnpm-lock.yaml
crawler/package.json
crawler/pnpm-lock.yaml
frontend/package.json
frontend/pnpm-lock.yaml

fix(*): add typescript

---

build/docker-compose.yml
build/template.env
e2e/__test__/pages/pages_snapshot.test.js

The ports are not exposed to public by default.

build(docker): improve security

---

build/docker-compose.yml
crawler/README.md
crawler/__test__/configReader.test.js
crawler/crawlers/vjudge.js
crawler/lib/configReader.js

Fix vjudge

---

crawler/__test__/crawlers.test.js
crawler/config.yml
crawler/crawlers/sdutoj.js

This PR adds [SDUT OJ](https://oj.sdutacm.cn/) crawler and its related test cases.
Hopefully you can review this PR soon and let me know if there are any changes that need to be made that I'm not aware of. 
Looking forward to the release of this new crawler.

feat(crawler): add sdutoj crawler
